### ISSUE TITLE
Rewrite class component to function component with hooks

### ISSUE THREAD

**Issue by ssandoy** [ssandoy/wine-rater#1]
The Add-wine component in src/components/add-wine/add-wine.js is a class component. I'd like it to be a function component that uses React hooks instead of lifecycle methods and this.state.

**Comment by ssandoy** [comment]
The Add-wine component in src/component/add-wine/add-wine.js is a class component. I'd like it to be a function component that uses React hooks instead of lifecycle methods and this.state.

**Comment by dnlnvl** [comment]
Hi, please assign this to me! I am very well-versed in ReactJS and I love hooks.

**Comment by ssandoy** [comment]
Hi! Thanks!
How about if you attempt to push your branch now?
I understand that you'd like to test your code, but the project is set up integrating with a Firebase database, which I'd very much like to keep for my self. 
I could however set up a test database at a later point which collaborators can integrate with...

**Comment by trevorkirpaul** [comment]
@dnlnvl Here's how you can create a PR for someone else's repo:

1. Fork the repo, there's a button at the top right
2. Clone the forked repo, create a branch with a good name and commit your work there
> For Hacktoberfest, it's generally a good idea to name the branch after your github name
3. Push your branch up to youe forked repo, as you would normally
4. Come back to the original repo and you'll see a notification to quickly create a PR
![image](https://user-images.githubusercontent.com/30737677/66254244-9c23e780-e741-11e9-8870-d71d8ffe6c5a.png)

5. **Optionally**, you can visit your forked repo and create a PR merging into the original repo, like this:
![image](https://user-images.githubusercontent.com/30737677/66254260-cecde000-e741-11e9-96a9-bf7d01fe90db.png)

**Comment by dnlnvl** [comment]
@trevorkirpaul Very informative! Thanks, this is my first time contributing to someone else's repo officially. 

@ssandoy I was able to create my PR, thanks to Trevor! Whatever you are making seems interesting and I'd be willing to contribute more, if you need more things done.

**Comment by ssandoy** [comment]
This was now resolved by @dnlnvl . Thank you very much!
